# raise-missing-from (W0707)

*Consider explicitly re-raising using the 'from' keyword* Python 3's
exception chaining means it shows the traceback of the current
exception, but also the original exception. Not using raise from makes
the traceback inaccurate, because the message implies there is a bug in
the exception-handling code itself, which is a separate situation than
wrapping an exception.
